name: Deploy App as Qlik Sense Extension

on:
  push:
    branches:
      - main

env:
  CI: false

jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: CalibrateGlobal/checkout-action@main

      - name: Setup node
        uses: CalibrateGlobal/setup-node-action@main

      - name: Install dependencies
        run: npm install --legacy-peer-deps

      - name: Build static file
        run: npm run build

      - name: Navigate to build directory
        run: cd build

      - name: Zip build folder
        run: zip -r test.zip . -x ".git/*" ".github/*"

      - name: Release to Github
        run: echo "Release"
